# Dockerfile.conda
FROM mambaorg/micromamba:0.23.1

ARG CONDA_DEPENDENCIES

# Create and activate the conda environment
RUN micromamba create --name conda_env ${CONDA_DEPENDENCIES} && \
    micromamba clean --all --yes

# Set the shell
SHELL ["micromamba", "run", "-n", "conda_env", "/bin/bash", "-c"]

# Set entrypoint
ENTRYPOINT ["micromamba", "run", "-n", "conda_env"]
